Migrate to Ubuntu 22.04. Close #13

diff --git a/retro-home-image b/retro-home-image
--- a/retro-home-image
+++ b/retro-home-image
@@ -1,14 +1,6 @@
 #!/usr/bin/env bash
 LC_ALL=C
 
-# TODO
-# - Add Plymouth splash
-# - Add 'ludo' user authentication for Samba
-# - Add Vivaldi browser?
-# - Add Joystick as mouse?
-# - Add N64 core
-# - Add Saturn core
-
 # Display help usage
 function usage () {
   echo
@@ -129,6 +121,10 @@ function stage_01_bootstrap() {
     echo "retro-home-${REMIX}" > "${R}/etc/hostname"
     sed -i "1s|.*|127.0.0.1\tlocalhost retro-home-${REMIX}|" "${R}/etc/hosts"
 
+    # Set locale to C.UTF-8 by default.
+    # https://git.launchpad.net/livecd-rootfs/tree/live-build/auto/build#n159
+    echo "LANG=C.UTF-8" > "${R}/etc/default/locale"
+
     nspawn apt-get -y update
 
     # Install Multicast DNS Service Discovery and first boot filesystem expansion
@@ -188,6 +184,8 @@ function stage_03_micro_desktop() {
         librsvg2-common mutter-common pulseaudio sakura transmission-gtk \
         yaru-theme-gtk yaru-theme-icon yaru-theme-sound
 
+        # Add the Raspberry Pi specific tweaks
+        nspawn apt-get -y install ubuntu-raspi-settings
         #wget -qc "https://downloads.vivaldi.com/stable/vivaldi-stable_4.3.2439.71-1_${IMG_ARCH}.deb" -O "${R_STAGE_0}/vivaldi-stable.deb"
         #cp "${R_STAGE_0}/vivaldi-stable.deb" "${R}/vivaldi-stable.deb"
         #nspawn apt-get -y install /vivaldi-stable.deb
@@ -212,16 +210,17 @@ function stage_04_kernel() {
     cp "boot/cmdline.txt" "${B}/"
     cp "root/etc/fstab" "${R}/etc/"
 
-    # No uboot since 20.10
     if [ "${IMG_ARCH}"  == "arm64" ]; then
-        ARM64="arm_64bit=1"
+        ARM64="# Config settings specific to arm64
+arm_64bit=1
+dtoverlay=dwc2"
     else
         ARM64=""
     fi
     sed -i "s|ARM64|${ARM64}|" "${B}/config.txt"
 
     nspawn apt-get -y install libraspberrypi0 libraspberrypi-bin \
-    linux-firmware-raspi2 linux-headers-raspi linux-image-raspi \
+    linux-firmware-raspi linux-headers-raspi linux-image-raspi \
     linux-modules-extra-raspi pi-bluetooth raspi-config rpi-eeprom
 
     local NEW_KERNEL=$(ls -1 "${R}"/boot/vmlinuz-* | tail -n1 | awk -F/ '{print $NF}' | cut -d'-' -f2-4)
@@ -232,7 +231,7 @@ function stage_04_kernel() {
     echo "Kernel: ${NEW_KERNEL}"
 
     # Copy firmware, devicetree, overlays and kernel to the boot file system
-    cp -v "${R}/lib/linux-firmware-raspi2/"* "${B}/"
+    cp -v "${R}/lib/linux-firmware-raspi/"* "${B}/"
     cp -av "${R}/lib/firmware/${NEW_KERNEL}/device-tree/"* "${B}/"
 
     # Move the arm64 device-tree
@@ -256,15 +255,6 @@ function stage_05_config() {
     local PASSWD=""
     PASSWD=$(mkpasswd -m sha-512 "${USER_PASS}" "${DATE}")
     nspawn addgroup --gid 1000 "${USER_NAME}"
-
-    # Create Raspberry Pi specific groups.
-    nspawn groupadd -f --system gpio
-    nspawn groupadd -f --system i2c
-    nspawn groupadd -f --system input
-    nspawn groupadd -f --system spi
-
-    cp "root/usr/local/sbin/adduser.local" "${R}/usr/local/sbin/"
-    chmod 755 "${R}/usr/local/sbin/adduser.local"
 
     nspawn adduser --gecos "${USER_NAME^}" --add_extra_groups --disabled-password --home "${USER_HOME}" --gid 1000 --uid 1000 "${USER_NAME}"
     nspawn usermod -a -G adm,sudo -p "${PASSWD}" "${USER_NAME}"
@@ -310,7 +300,7 @@ function stage_05_config() {
         cp "root/etc/samba/smb.conf" "${R}/etc/samba/"
         sed -i "s|REMIX|${REMIX}|g" "${R}/etc/samba/smb.conf"
 
-        # Create directozries Ludo requires
+        # Create directories Ludo requires
         for DOT_DIR in .cache/connman .cache/services .config/ludo .local/ludo .local/share/ludo .ludo .update; do
             mkdir -p "${R}/storage/${DOT_DIR}"
         done
@@ -547,7 +537,7 @@ function stage_07_image() {
     rm -rf "${MOUNTDIR}"
 }
 
-function stage_08_compress_and_hash() {
+function stage_08_compress() {
     export B="${B_STAGE_6}"
     export R="${R_STAGE_6}"
 
@@ -571,9 +561,11 @@ function stage_08_compress_and_hash() {
     fi
 }
 
-if [ "$(id -u)" -ne 0 ]; then
-    echo "ERROR! Root permissions required."
-    exit 1
+if [ -z "${SUDO_USER}" ]; then
+  echo "ERROR! You must use sudo to run this script: sudo ./$(basename ${0})"
+  exit 1
+else
+  SUDO_HOME=$(getent passwd "${SUDO_USER}" | cut -d: -f6)
 fi
 
 # Take command line arguments
@@ -701,23 +693,15 @@ esac
 
 # Install apt-cacher-ng on the host and this script will use it.
 APT_CACHE_IP=$(ip route get 1.1.1.1 | head -n 1 | cut -d' ' -f 7)
-IMG_QUALITY="-alpha5"
-IMG_VER="21.10"
-IMG_RELEASE="impish"
+IMG_QUALITY="-alpha1"
+IMG_VER="22.04"
+IMG_RELEASE="jammy"
 IMG_ARCH="armhf"
 IMG_OUT="retro-home-${REMIX}-${IMG_VER}${IMG_QUALITY}-${IMG_ARCH}.img"
 USER_NAME="ludo"
 USER_PASS="retro"
 USER_HOME="/storage"
-
-# Determine where to cache & build the images
-if [ -n "${SUDO_USER}" ]; then
-    SUDO_HOME=$(eval echo "~${SUDO_USER}")
-else
-    SUDO_HOME="${HOME}"
-fi
-TMP_DIR="${SUDO_HOME}/Pi"
-mkdir -p "${TMP_DIR}" 2>/dev/null
+TMP_DIR="${SUDO_HOME}/Builds"
 
 # Create caches
 for LOOP in 0 1 2 3 4 5 6 7 8 9; do
@@ -742,4 +726,4 @@ stage_04_kernel
 stage_05_config
 stage_06_clean
 stage_07_image
-stage_08_compress_and_hash
+stage_08_compress
